DocOffice/Models/Doctor.cs
using System.Collections.Generic;

namespace DocOffice.Models
{
  public class Doctor
  {
    public Doctor()
    {
      this.JoinEntities = new HashSet<DoctorPatient>();
    }

    public int DoctorId { get; set; }
    public string Name { get; set; }
    public string Specialty { get; set; }
    public virtual ICollection<DoctorPatient> JoinEntities { get; set; }
  }
}

DocOffice/Controllers/DoctorController.cs
using DocOffice.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace DocOffice.Controllers
{
  public class DoctorsController : Controller
  {
    private readonly DocOfficeContext _db;

    public DoctorsController(DocOfficeContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Doctors.ToList());
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Doctor doctor)
    {
      _db.Doctor.Add(doctor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisDoctor = _db.Doctors
        .Include(doctor => doctor.JoinEntities)
        .ThenInclude(join => join.Doctor)
        .FirstOrDefault(doctor => doctor.DoctorId == id);
      return View(thisDoctor);
    }
  }
}

DocOffice/Controllers/DoctorsController.cs
using DocOffice.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace DocOffice.Controllers
{
  public class DoctorsController : Controller
  {
    private readonly DocOfficeContext _db;

    public DoctorsController(DocOfficeContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Doctors.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.SpecialtyId = new SelectList(_db.Specialties, "SpecialtyId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Doctor doctor, int SpecialtyId)
    {
      _db.Doctors.Add(doctor);
      _db.SaveChanges();
      if (SpecialtyId != 0)
      {
        _db.DoctorSpecialty.Add(new DoctorSpecialty() {DoctorId = doctor.DoctorId, SpecialtyId = SpecialtyId});
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisDoctor = _db.Doctors
        .Include(doctor => doctor.JoinEntities)
        .ThenInclude(join => join.Doctor)
        .Include(doctor => doctor.JoinEntSpec)
        .ThenInclude(join => join.Doctor)
        .FirstOrDefault(doctor => doctor.DoctorId == id);
      return View(thisDoctor);
    }

    public ActionResult Edit(int id)
    {
      var thisDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
      ViewBag.SpecialtyId = new SelectList(_db.Specialties, "SpecialtyId", "Name");
      return View(thisDoctor);
    }

    [HttpPost]
    public ActionResult Edit(Doctor doctor)
    {
      _db.Entry(doctor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
      return View(thisDoctor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Doctor thisDoctor = _db.Doctors.FirstOrDefault(doctor => doctor.DoctorId == id);
      _db.Doctors.Remove(thisDoctor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    
    public ActionResult AddSpecialty(int id)
    {
      Doctor thisDoctor = _db.Doctors
        .Include(doctor => doctor.JoinEntities)
        .ThenInclude(join => join.Doctor)
        .FirstOrDefault(doctor => doctor.DoctorId == id);
      ViewBag.SpecialtyId = new SelectList(_db.Specialties, "SpecialtyId", "Name");
      return View(thisDoctor);
    }

    [HttpPost]
    public ActionResult AddSpecialty(Doctor doctor, int SpecialtyId)
    {
      if (SpecialtyId != 0)
      {
        _db.DoctorSpecialty.Add(new DoctorSpecialty() {SpecialtyId = SpecialtyId, DoctorId = doctor.DoctorId});
        _db.SaveChanges();
      }
    return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteSpecialty(int joinId)
    {
      var thisJoin = _db.DoctorSpecialty.FirstOrDefault(specialty => specialty.DoctorSpecialtyId == joinId);
      _db.DoctorSpecialty.Remove(thisJoin);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

DocOffice/Controllers/PatientsController.cs
using DocOffice.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace DocOffice.Controllers
{
  public class PatientsController : Controller
  {
    private readonly DocOfficeContext _db;

    public PatientsController(DocOfficeContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Patients.ToList());
    }

    public ActionResult Create()
    {
			ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Patient patient, int DoctorId)
    {
      _db.Patients.Add(patient);
      _db.SaveChanges();
			if (DoctorId != 0)
			{
				_db.DoctorPatient.Add(new DoctorPatient() {DoctorId = DoctorId, PatientId = patient.PatientId });
				_db.SaveChanges();
			}
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisPatient = _db.Patients
        .Include(patient => patient.JoinEntities)
        .ThenInclude(join => join.Patient)
        .FirstOrDefault(patient => patient.PatientId == id);
      return View(thisPatient);
    }

    public ActionResult Edit(int id)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patient => patient.PatientId == id);
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      return View(thisPatient);
    }

    [HttpPost]
    public ActionResult Edit(Patient patient, int DoctorId)
    {
      if (DoctorId != 0)
      {
        _db.DoctorPatient.Add(new DoctorPatient() { DoctorId = DoctorId, PatientId = patient.PatientId});
      }
        _db.Entry(patient).State = EntityState.Modified;
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisPatient = _db.Patients.FirstOrDefault(patient => patient.PatientId == id);
      return View(thisPatient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Patient thisPatient = _db.Patients.FirstOrDefault(patient => patient.PatientId == id);
      _db.Patients.Remove(thisPatient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddDoctor(int id)
    {
      Patient thisPatient = _db.Patients
        .Include(patient => patient.JoinEntities)
        .ThenInclude(join => join.Patient)
        .FirstOrDefault(patient => patient.PatientId == id);
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      return View(thisPatient);
    }

    [HttpPost]
    public ActionResult AddDoctor(Patient patient, int DoctorId)
    {
      if (DoctorId != 0)
      {
        _db.DoctorPatient.Add(new DoctorPatient() {DoctorId = DoctorId, PatientId = patient.PatientId});
        _db.SaveChanges();
      }
    return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteDoctor(int joinId)
    {
      var thisJoin = _db.DoctorPatient.FirstOrDefault(doctor => doctor.DoctorPatientId == joinId);
      _db.DoctorPatient.Remove(thisJoin);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

DocOffice/Controllers/SpecialtiesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using DocOffice.Models;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace DocOffice.Controllers
{
	public class SpecialtiesController : Controller
	{
		private readonly DocOfficeContext _db;

		public SpecialtiesController(DocOfficeContext db)
		{
			_db = db;
		}

		public ActionResult Index()
		{
			return View(_db.Specialties.ToList());
		}

		public ActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Create(Specialty specialty)
		{
			_db.Specialties.Add(specialty);
			_db.SaveChanges();
			return RedirectToAction("Index");
		}

		public ActionResult Details(int id)
		{
			Specialty thisSpec = _db.Specialties
				.Include(specialty => specialty.JoinEntSpec)
				.ThenInclude(join => join.Specialty)
				.FirstOrDefault(specialty => specialty.SpecialtyId == id);
			return View(thisSpec);
		}

		public ActionResult Edit(int id)
		{
			Specialty thisSpec = _db.Specialties.FirstOrDefault(specialty => specialty.SpecialtyId == id);
			return View(thisSpec);
		}

		[HttpPost]
		public ActionResult Edit(Specialty specialty)
		{
			_db.Entry(specialty).State = EntityState.Modified;
			_db.SaveChanges();
			return RedirectToAction("Index");
		}

		public ActionResult Delete(int id)
		{
			Specialty thisSpec = _db.Specialties.FirstOrDefault(specialty => specialty.SpecialtyId == id);
			return View(thisSpec);
		}

		[HttpPost, ActionName("Delete")]
		public ActionResult DeleteConfirmed(int id)
		{
			Specialty thisSpec = _db.Specialties.FirstOrDefault(specialty => specialty.SpecialtyId == id);
			_db.Specialties.Remove(thisSpec);
			_db.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

DocOffice/Views/Doctors/AddSpecialty.cshtml
@{
  Layout = "_Layout";
}

@model DocOffice.Models.Doctor

<h1>ADDING A SPECIALTY TO DOCTOR</h1>

<h4>Add a specialty to doctor @Html.DisplayFor(model => model.Name)</h4>

@using (@Html.BeginForm())
{
  @Html.HiddenFor(model => model.DoctorId)

  @Html.Label("Select the specialty")
  @Html.DropDownList("SpecialtyId")

  <input type="submit" value="Save"/>
}

<p>@Html.ActionLink("View all doctors", "Index")</p>

DocOffice/Views/Doctors/Create.cshtml
@{
	Layout = "_Layout";
}

@model DocOffice.Models.Doctor

<h2>Who's the Doc</h2>

@using (Html.BeginForm())
{
	@Html.LabelFor(model => model.Name)
	@Html.TextBoxFor(model => model.Name)
	@Html.Label("Specialty")
	@Html.DropDownList("SpecialtyId")

	<input type="submit" value="Add Doc">
}

<p>@Html.ActionLink("Create a Patient Profile", "Create", "Patients")</p>
<p>@Html.ActionLink("See All Patients", "Index", "Patients")</p>
<p>@Html.ActionLink("See All Doctors", "Index")</p>
<p>@Html.ActionLink("Return Home", "Index", "Home")</p>

DocOffice/Views/Doctors/Delete.cshtml
@{
	Layout = "_Layout";
}

@using DocOffice.Models;

<h2>WARNING</h2>
<h4>This doctor took an oath to do no harm.  If you decide to delete their record, you will be harming them.  It's ironic.  In a sad way.</h4>

@using (Html.BeginForm())
{
	<p>Delete the record of @Model.Name</p>
	<input type="submit" label="Confirm">
}

<p>@Html.ActionLink("See All Patients", "Index", "Patients")</p>
<p>@Html.ActionLink("See All Doctors", "Index")</p>
<p>@Html.ActionLink("Return Home", "Index", "Home")</p>

DocOffice/Views/Doctors/Details.cshtml
@{
	Layout = "_Layout";
}

@using DocOffice.Models;

<h3>Details on @Model.Name</h3>

@if (Model.JoinEntSpec.Count == 0)
{
	<p>This Doctor has no specialties!</p> 
}

<ul>
	@foreach(var join in Model.JoinEntSpec)
	{
		<li>@Html.ActionLink($"{join.Specialty.Name}", "Details", "Specialties", new { id = join.Specialty.SpecialtyId})</li>
    @using (Html.BeginForm("DeleteSpecialty", "Doctors"))
    {
      @Html.Hidden("joinId", @join.DoctorSpecialtyId)
      <input type="submit" value="Delete"/>
    }
	}
</ul>

@if (Model.JoinEntities.Count == 0)
{
	<p>This Doc has no patients (or friends :'( )</p>
}

<ul>
	@foreach (var join in Model.JoinEntities)
	{
		<li>@Html.ActionLink($"{join.Patient.Name}", "Details", "Patients", new { id = join.Patient.PatientId})</li>
	}
</ul>

<p>@Html.ActionLink("Add a Specialty to this Doctor", "AddSpecialty", new {id = Model.DoctorId })</p>
<p>@Html.ActionLink("Create a Patient Profile", "Create", "Patients")</p>
<p>@Html.ActionLink("Create a Doc Profile", "Create")</p>
<p>@Html.ActionLink("Edit this Doctor's Info", "Edit", new { id = Model.DoctorId })</p>
<p>@Html.ActionLink("Delete this Doctor", "Delete", new { id = Model.DoctorId })</p>
<p>@Html.ActionLink("See All Patients", "Index", "Patients")</p>
<p>@Html.ActionLink("See All Doctors", "Index")</p>
<p>@Html.ActionLink("Return Home", "Index", "Home")</p>

DocOffice/Views/Doctors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model DocOffice.Models.Doctor

<h1>EDIT</h1>

<h3>You are editing the information for the Doctor: @Html.DisplayFor(model => model.Name)</h3>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.DoctorId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.Label("Specialty")
  @Html.DropDownList("SpecialtyId")

  <input type="submit" value="Save"/>
}

<p>@Html.ActionLink("See All Patients", "Index", "Patients")</p>
<p>@Html.ActionLink("See All Doctors", "Index")</p>
<p>@Html.ActionLink("Return Home", "Index", "Home")</p>

DocOffice/Views/Doctors/Index.cshtml
@{
	Layout = "_Layout";
}

@using DocOffice.Models;
<h2>All doctors:</h2>

@if (Model.Count == 0)
{
	<p>We have no Docs :(</p>
}

<ul>
@foreach (Doctor doctor in Model)
{
	<li>@Html.ActionLink($"{doctor.Name}", "Details", new {id = doctor.DoctorId})</li>
}
</ul>

<p>@Html.ActionLink("Create a Doc Profile", "Create")</p>
<p>@Html.ActionLink("Create a Patient Profile", "Create", "Patients")</p>
<p>@Html.ActionLink("See All Patients", "Index", "Patients")</p>
<p>@Html.ActionLink("Return Home", "Index", "Home")</p>